### ISSUE TITLE
"Show GLSL" toggle crashes the simulator

### ISSUE THREAD

**Issue by bencbartlett** [baaahs/sparklemotion#452]
Toggling the "show GLSL" switch crashes the simulator on the current build at https://baaahs.github.io/sparklemotion/, causing it to show a grey screen indefinitely. Tested on apple silicon and windows using both chrome and firefox.

**Comment by xian** [comment]
Oops! Looks like I broke that when I added Patch Diagnostics to the client visualizer. Will fix!

```
TypeError: Cannot read properties of undefined (reading 'allStyles')
    at PaletteView.kt:30:33
    at XBuilder.kt:30:18
    at kotlin-react-legacy.js:57:7
    at O (kotlin-react-legacy.js:231:5)
    at kotlin-react-legacy.js:63:14
    at ba (react-dom.production.min.js:166:137)
    at bl (react-dom.production.min.js:289:386)
    at yc (react-dom.production.min.js:279:389)
    at gc (react-dom.production.min.js:279:320)
    at mc (react-dom.production.min.js:279:180)
ss @ react-dom.production.min.js:186
```
